version: "3.7"
services:
  search-application-frontend:
    image: rick043/search-application-frontend:0.3
    container_name: search-application-frontend
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    expose:
      - 80
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true