version: "3.7"
services:
  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn-as
    restart: unless-stopped
    cap-add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INTERFACE=bond0
    volumes:
      - ${CONF_DIR}/openvpn/config:/config
      - ${CLOUD_DIR}:/data
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true