version: "3.7"
services:
  xteve:
    container_name: xteve
    image: alturismo/xteve
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/xteve/config:/config:rw
    ports:
      - "34400:34400"
      - "1901:1900"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true