version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9-management
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    expose:
      - 15672
    ports:
      - 5672:5672
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.applied-science.entrypoints=https"
      - "traefik.http.routers.applied-science.rule=Host(`queue.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.applied-science.tls=true"
      - "traefik.http.routers.applied-science.middlewares=chain-no-auth@file"
      - "traefik.http.routers.applied-science.service=applied-science"
      - "traefik.http.services.applied-science.loadbalancer.server.port=15672"