version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  applied-science:
    container_name: applied-science
    image: rick043/applied-science
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - traefik_proxy
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.applied-science.entrypoints=https"
      - "traefik.http.routers.applied-science.rule=Host(`s6-appliedscience.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.applied-science.tls=true"
      - "traefik.http.routers.applied-science.middlewares=chain-no-auth@file"
      - "traefik.http.routers.applied-science.service=applied-science"
      - "traefik.http.services.applied-science.loadbalancer.server.port=8080"