version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  mc-exporter:
    container_name: mc-exporter
    image: ghcr.io/dirien/minecraft-exporter
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/minecraft/data/alloffabric6/FeedTheBeast/world:/minecraft/world
    networks:
      - traefik_proxy
    ports:
      - 9150:9150