version: "3.7"
services:
  diun:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - ${CONF_DIR}/homeassistant/shared:/shared
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true