version: "3.8"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INFLUXDB_ADMIN_USER=${MYSQL_USER}
      - INFLUXDB_ADMIN_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${CONF_DIR}/influxdb/data:/var/lib/influxdb
      - ${CONF_DIR}/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${CONF_DIR}/influxdb/init:/docker-entrypoint-initdb.d
    networks:
      - traefik_proxy
    expose:
      - 8086
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.entrypoints=https"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ${CONF_DIR}/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - traefik_proxy

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: unless-stopped
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${MYSQL_USER}
      - INFLUXDB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - traefik_proxy
    expose:
      - 8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.entrypoints=https"
      - "traefik.http.routers.chronograf.rule=Host(`chronograf.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.chronograf.tls=true"
      - "traefik.http.routers.chronograf.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.chronograf.service=chronograf"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"