version: "3.7"
services:
  archi:
    image: justarchi/archisteamfarm:latest
    container_name: archi
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ASF_CRYPTKEY=${ASF_CRYPTKEY}
      - ASF_ARGS=--no-config-migrate
    volumes:
      - ${CONF_DIR}/archi/config:/app/config
    networks:
      - traefik_proxy
    expose:
      - 1242
    ports:
      - 1242:1242
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.archi-rtr.entrypoints=https"
      - "traefik.http.routers.archi-rtr.rule=Host(`archi.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.traefik-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.archi-rtr.service=archi-svc"
      - "traefik.http.services.archi-svc.loadbalancer.server.port=1242"