version: "3.7"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/sonarqube/data:/opt/sonarqube/data
      - ${CONF_DIR}/sonarqube/extensions:/opt/sonarqube/extensions
    expose:
      - 9000
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true