version: "3.7"
services:
  xteve:
    container_name: xteve
    image: alturismo/xteve
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/xteve/config:/config:rw
    networks:
      - traefik_proxy
    ports:
      - "34400:34400"
      - "1901:1900"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.xteve-rtr.entrypoints=https"
      - "traefik.http.routers.xteve-rtr.rule=Host(`xteve.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.xteve-rtr.tls=true"
      - "traefik.http.routers.xteve-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.xteve-rtr.service=xteve-svc"
      - "traefik.http.services.xteve-svc.loadbalancer.server.port=34400"