version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  postgres:
    image: postgres:12.6
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${CONF_DIR}/postgres:/var/lib/postgresql/data
    networks:
      - traefik_proxy
    ports:
      - 5432:5432
    shm_size: 256M