version: "3.7"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    volumes:
      - ${CONF_DIR}/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    expose:
      - 80
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true