version: "3.7"
services:
  team-city:
    image: jetbrains/teamcity-server
    container_name: team-city
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/team-city/datadir:/data/teamcity_server/datadir
      - ${CONF_DIR}/team-city/logs:/opt/teamcity/logs
      - ${CONF_DIR}/team-city/config:/opt/teamcity/conf }
    expose:
      - 8111
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - diun.enable=true
      - diun.watch_repo=true